server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/neuroassist;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: "change-this-dev-secret-key"
    expirationMinutes: 1440
  openai:
    apiKey: ""
